### ISSUE TITLE
Can't find the camera in Homekit

### ISSUE THREAD

**Issue by mokrol** [rasod/homebridge-kunalight#3]
Not sure what I am doing wrong but I can not get the Kuna camera image to show in HK. When I go to the URL (http://127.0.0.1:3000/thumbnail) directly I can see the image. From what I can tell my config is set up correctly:

Kuna
```
    {
            "accessory": "Kuna",
            "name": "Front Door",
            "email": "EMAIL",
            "password": "PASSWORD",
            "serial": "SERIAL",
            "proxyThumbnail": true,
            "proxyPort": 3000,
            "polling": 1
        },

```
FFMPEG
```
   {
            "name": "Camera ffmpeg",
            "cameras": [
                {
                    "name": "Front Door",
                    "videoConfig": {
                        "source": "-i http://127.0.0.1:3000/thumbnail",
                        "stillImageSource": "-i http://127.0.0.1:3000/thumbnail",
                        "maxStreams": 1,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 30,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "packetSize": 1316,
                        "audio": false,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }  
```
But when I try to add to HK by entering the code, Setup Code: 031-45-154 It never finds it. I tried resetting the Kuna but nothing is working. Am I missing something on this?

BTW - This is the detail I get from the log:

```
Dec 18 09:42:09 raspberrypi homebridge[6392]: [12/18/2019, 9:42:09 AM] Front Door is running on port 40095.
Dec 18 09:42:09 raspberrypi homebridge[6392]: [12/18/2019, 9:42:09 AM] Please add [Front Door] manually in Home app. Setup Code: 031-45-154
Dec 18 09:42:09 raspberrypi homebridge[6392]: [12/18/2019, 9:42:09 AM] [Front Door] Proxying Thumbnail Enabled Use URL: http://127.0.0.1:3000/thumbnail
Dec 18 09:42:09 raspberrypi homebridge[6392]: [12/18/2019, 9:42:09 AM] [Front Door] Getting current state...
```

**Comment by rasod** [comment]
Does the camera show when you try to add it, or are you adding the code manually?

**Comment by mokrol** [comment]
No, it does not show at all.

**Comment by rasod** [comment]
Hmm, I don’t know if this matters maybe the camera and light can’t have the same name? In my config they are different - I don’t think that is it but not sure. The Kuna plugin doesn’t actually create the camera, from your log it looks like the Camera is being created.

**Comment by mokrol** [comment]
Changing the name tonight to see if this works.

**Comment by mokrol** [comment]
Sorry for the delayed replay but wanted to share that the name changed corrected the issue and i now see the cam. Thanks for your help.

**Comment by rasod** [comment]
great I'll update the documentation

**Comment by mick101** [comment]
I'm coming across the same type of situation but light and camera have different names.
Here's the debug:

[Camera FFmpeg] [DoorCam] Snapshot requested: 1280 x 720
[DoorCam AB43] Snapshot request handler provided empty image buffer!
